In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("diamonds.csv")
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [4]:
df = pd.read_csv("diamonds.csv")

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df = df.drop_duplicates()

In [7]:
df = df.drop("Unnamed: 0", axis=1)
X = df.drop("price", axis=1)
y = df["price"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
cat_cols = ['cut','color','clarity']

In [10]:
encoder = OneHotEncoder(
    drop='first',
    sparse_output=False,
    handle_unknown='ignore'
)

In [11]:
X_train_encoded = encoder.fit_transform(X_train[cat_cols])

In [12]:
X_test_encoded = encoder.transform(X_test[cat_cols])

In [13]:
encoded_columns = encoder.get_feature_names_out(cat_cols)
encoded_columns

array(['cut_Good', 'cut_Ideal', 'cut_Premium', 'cut_Very Good', 'color_E',
       'color_F', 'color_G', 'color_H', 'color_I', 'color_J',
       'clarity_IF', 'clarity_SI1', 'clarity_SI2', 'clarity_VS1',
       'clarity_VS2', 'clarity_VVS1', 'clarity_VVS2'], dtype=object)

In [14]:
X_train_encoded = pd.DataFrame(
    X_train_encoded,
    columns=encoded_columns,
    index=X_train.index
)

X_test_encoded = pd.DataFrame(
    X_test_encoded,
    columns=encoded_columns,
    index=X_test.index
)

In [15]:
X_train = X_train.drop(columns=cat_cols)
X_test = X_test.drop(columns=cat_cols)

In [16]:
X_train = pd.concat([X_train, X_train_encoded], axis=1)
X_test = pd.concat([X_test, X_test_encoded], axis=1)

In [17]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
model = LinearRegression()

In [19]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
r2 = r2_score(y_test, y_pred)
print(r2)

0.9189331350419386

In [22]:
result = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_pred
})

In [23]:
result.head(10)

       Actual Price  Predicted Price
1388            559       711.885773
50052          2201      3191.725837
41645          1238      1947.246411
42377          1304      2077.290626
17244          6901      9878.998209
1608           3011      3932.584825
46398          1765      2372.625853
45493          1679      2380.087067
49385          2102      2844.118276
10460          4789      6199.238917

In [24]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
dt_model = DecisionTreeRegressor(
    random_state=42
)

In [26]:
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [27]:
dt_pred = dt_model.predict(X_test)

In [28]:
dt_r2 = r2_score(y_test, dt_pred)
print("R² Score :", dt_r2)

R² Score : 0.9549380236953803

In [29]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree"],
    "R² Score": [r2, dt_r2],
    
})

comparison

               Model  R² Score
0  Linear Regression  0.918933
1      Decision Tree  0.954938

In [30]:
import joblib

In [31]:
joblib.dump(model, "SimpleLinear.joblib")
joblib.dump(dt_model, "DecisionTree.joblib")

['DecisionTree.joblib']

In [32]:
#if you are using dump model in streamlit app, then you also have to dump endong and scaling file
joblib.dump(encoder, "encoder.joblib")
joblib.dump(scaler, "scaler.joblib")

['scaler.joblib']